# fly.toml app configuration file generated for mdwreferencias on 2025-05-03T18:59:25-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mdwreferencias'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
