INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Átrio Direito 4 Câmaras', 'VR_AD_A4C', 'Átrio Direito 4 Câmaras', 
        1, 'ADA4C', 'ADA4C', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Átrio Esquerdo 2 Câmaras', 'VR_AE_A2C', 'Átrio Esquerdo 2 Câmaras', 
        1, 'AEA2C', 'AEA2C', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Átrio Esquerdo 4 Câmaras', 'VR_AE_A4C', 'Átrio Esquerdo 4 Câmaras', 
        1, 'AEA4C', 'AEA4C', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Aorta Anel I', 'VR_AO_ANEL_I', 'Aorta Anel I', 
        1, 'AOAI', 'AOAI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Aorta Ascendente Proximal', 'VR_AO_ASC_PROX', 'Aorta Ascendente Proximal', 
        1, 'AOASCPROX', 'AOASCPROX', 
        2, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Aorta Ascendente Proximal I', 'VR_AO_ASC_PROX_I', 'Aorta Ascendente Proximal I', 
        1, 'AOASCPROXI', 'AOASCPROXI', 
        2, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Aorta Junção', 'VR_AO_JUNCAO', 'Aorta Junção', 
        1, 'AOJUNCAO', 'AOJUNCAO', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Aorta Junção I', 'VR_AO_JUNCAO_I', 'Aorta Junção I', 
        1, 'AOJUNCAOI', 'AOJUNCAOI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Aorta Seio Valsalva I', 'VR_AO_SEIO_VALSALVA_I', 'Aorta Seio Valsalva I', 
        1, 'AOSVI', 'AOSVI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Aorta Seio Valsalva', 'VR_AO_SV', 'Aorta Seio Valsalva', 
        1, 'AOSV', 'AOSV', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Arco Aórtico', 'VR_ARCOAO', 'Arco Aórtico', 
        1, 'ARCOAO', 'ARCOAO', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Atriodireitoarea', 'VR_ATRIODIREITOAREA', 'Atriodireitoarea', 
        1, 'A', 'A', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'A Pulmonar', 'VR_A_PULMONAR', 'A Pulmonar', 
        1, 'AP', 'AP', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Compae L', 'VR_COMPAE_L', 'Compae L', 
        1, 'CL', 'CL', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'dP/dT do Ventrículo Esquerdo', 'VR_DPDTVE', 'dP/dT do Ventrículo Esquerdo', 
        1, 'DPDTVE', 'DPDTVE', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'dP/dT Ventrículo Direito', 'VR_DPDT_VD', 'dP/dT Ventrículo Direito', 
        1, 'DPDTVD', 'DPDTVD', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Desaceleração Átrio Lateral', 'VR_DSATL', 'Desaceleração Átrio Lateral', 
        1, 'DSATL', 'DSATL', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Deceleração Vsvd', 'VR_DT_VSVD', 'Deceleração Vsvd', 
        1, 'DTV', 'DTV', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Duracao Onda A Mitral', 'VR_DURACAO_ONDA_A_MITRAL', 'Duracao Onda A Mitral', 
        1, 'DOAM', 'DOAM', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Espessura Relativa Paredes', 'VR_ERP', 'Espessura Relativa Paredes', 
        1, 'ERP', 'ERP', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Espessura Ventrículo Direito', 'VR_EVD', 'Espessura Ventrículo Direito', 
        1, 'EVD', 'EVD', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Fração de Área Ventrículo Direito', 'VR_FAC_VD', 'Fração de Área Ventrículo Direito', 
        1, 'FACVD', 'FACVD', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Fração Ejeção Simpson Manual', 'VR_FESIMPSON_MANUAL', 'Fração Ejeção Simpson Manual', 
        1, 'FESIMPSONM', 'FESIMPSONM', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Strain Livre Ventrículo Direito', 'VR_FWSVD', 'Strain Livre Ventrículo Direito', 
        1, 'FWSVD', 'FWSVD', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Strain Global Ventrículo Direito', 'VR_GLSVD', 'Strain Global Ventrículo Direito', 
        1, 'GLSVD', 'GLSVD', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Indiceelinha', 'VR_INDICEELINHA', 'Indiceelinha', 
        1, 'I', 'I', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Indiceelinha Lat', 'VR_INDICEELINHA_LAT', 'Indiceelinha Lat', 
        1, 'IL', 'IL', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'MAPSE', 'VR_MAPS', 'MAPSE', 
        1, 'MAPS', 'MAPS', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Media E Elinha', 'VR_MEDIA_E_ELINHA', 'Media E Elinha', 
        1, 'MEE', 'MEE', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Massa do Ventrículo Esquerdo Altura', 'VR_MVE_ALTURA', 'Massa do Ventrículo Esquerdo Altura', 
        1, 'MVEA', 'MVEA', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Pad', 'VR_PAD', 'Pad', 
        1, 'P', 'P', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Percentual Encurtamento', 'VR_PEC', 'Percentual Encurtamento', 
        1, 'PEC', 'PEC', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Pressão de Pico Calculada', 'VR_PPICO_CALCULADA', 'Pressão de Pico Calculada', 
        1, 'PPICOC', 'PPICOC', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Pressao Átrio Direito', 'VR_PRESSAO_AD', 'Pressao Átrio Direito', 
        1, 'PAD', 'PAD', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Relação E A', 'VR_REL_E_A', 'Relação E A', 
        1, 'RELEA', 'RELEA', 
        2, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Relação E E Linha', 'VR_REL_E_E_LINHA', 'Relação E E Linha', 
        1, 'RELEELINHA', 'RELEELINHA', 
        2, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Strain Global Longitudinal', 'VR_SGL', 'Strain Global Longitudinal', 
        1, 'SGL', 'SGL', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Strain Global Longitudinal Átrio Esquerdo', 'VR_SGL_AE', 'Strain Global Longitudinal Átrio Esquerdo', 
        1, 'SGLAE', 'SGLAE', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Strain Linha', 'VR_SLINHA', 'Strain Linha', 
        1, 'SLINHA', 'SLINHA', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Tempo Desaceleracao E Mitral', 'VR_TEMPO_DESACELERACAO_E_MITRAL', 'Tempo Desaceleracao E Mitral', 
        1, 'TDEM', 'TDEM', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Átrio Direito Indexado', 'VR_VAD_SC', 'Volume Átrio Direito Indexado', 
        1, 'VADSC', 'VADSC', 
        2, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Vae Altura', 'VR_VAE_ALTURA', 'Vae Altura', 
        1, 'VA', 'VA', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Velocidade Átrio Lateral', 'VR_VATL', 'Velocidade Átrio Lateral', 
        1, 'VATL', 'VATL', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Diastólico Final Bi', 'VR_VDF_BI', 'Volume Diastólico Final Bi', 
        1, 'VDFB', 'VDFB', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Diastólico Final Bi I', 'VR_VDF_BI_I', 'Volume Diastólico Final Bi I', 
        1, 'VDFBI', 'VDFBI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Diastólico Final I', 'VR_VDF_I', 'Volume Diastólico Final I', 
        1, 'VDFI', 'VDFI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Ventrículo Direito Area Diastólica', 'VR_VD_AREA_DIASTOLE', 'Ventrículo Direito Area Diastólica', 
        1, 'VDAD', 'VDAD', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Ventrículo Direito Area Sistólica', 'VR_VD_AREA_SISTOLE', 'Ventrículo Direito Area Sistólica', 
        1, 'VDAS', 'VDAS', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Ventrículo Direito Baseapice', 'VR_VD_BASEAPICE', 'Ventrículo Direito Baseapice', 
        1, 'VDB', 'VDB', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Ventrículo Direito Base-Topo', 'VR_VD_BT', 'Ventrículo Direito Base-Topo', 
        1, 'VDBT', 'VDBT', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Ventrículo Direito Medio', 'VR_VD_MEDIO', 'Ventrículo Direito Medio', 
        1, 'VDM', 'VDM', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Ventrículo Esquerdo Diastólico Indexado', 'VR_VEDI', 'Ventrículo Esquerdo Diastólico Indexado', 
        1, 'VEDI', 'VEDI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Velocidade Inicial Regurgitação Pulm', 'VR_VEL_INICIAL_REG_PULM', 'Velocidade Inicial Regurgitação Pulm', 
        1, 'VELIREGP', 'VELIREGP', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Velocidade Regurgitação Tricuspide', 'VR_VEL_REG_TRICUSPIDE', 'Velocidade Regurgitação Tricuspide', 
        1, 'VELREGT', 'VELREGT', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Sistólico Final Bi', 'VR_VSF_BI', 'Volume Sistólico Final Bi', 
        1, 'VSFB', 'VSFB', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Sistólico Final Bi I', 'VR_VSF_BI_I', 'Volume Sistólico Final Bi I', 
        1, 'VSFBI', 'VSFBI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Sistólico Final I', 'VR_VSF_I', 'Volume Sistólico Final I', 
        1, 'VSFI', 'VSFI', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
INSERT INTO VARIAVEIS (
        NOME, VARIAVEL, DESCRICAO, CODUNIDADEMEDIDA, SIGLA, 
        ABREVIACAO, CASASDECIMAIS, CODUSUARIO, DTHRULTMODIFICACAO
    ) VALUES (
        'Volume Sistólico Ventrículo Esquerdo', 'VR_VSVE', 'Volume Sistólico Ventrículo Esquerdo', 
        1, 'VSVE', 'VSVE', 
        NULL, 
        4, CURRENT_TIMESTAMP
    );
