CREATE TABLE REFERENCIA (
    CODREFERENCIA INT AUTO_INCREMENT PRIMARY KEY,
    AUTOR VARCHAR(255),
    ANO INT
);

CREATE TABLE METODO_MEDIDA (
    CODMETODO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE MODO_IMAGEM (
    CODMODO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE TIPO_EXAME (
    CODTIPOEXAME INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE VARIAVEIS (
    CODVARIAVEL INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    UNIDADE VARCHAR(50),
    CODMETODO INT,
    CODMODO INT,
    CODTIPOEXAME INT,
    CONSTRAINT VARIAVEIS_METODO_FK FOREIGN KEY (CODMETODO) REFERENCES METODO_MEDIDA(CODMETODO),
    CONSTRAINT VARIAVEIS_MODO_FK FOREIGN KEY (CODMODO) REFERENCES MODO_IMAGEM(CODMODO),
    CONSTRAINT VARIAVEIS_TIPOEXAME_FK FOREIGN KEY (CODTIPOEXAME) REFERENCES TIPO_EXAME(CODTIPOEXAME)
);

CREATE TABLE FORMULAS (
    CODFORMULA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    DESCRICAO VARCHAR(255),
    FORMULA TEXT,
    CASADECIMAIS INT,
    UNIDADE_MEDIDA VARCHAR(50),
    CODREFERENCIA INT,
    CONSTRAINT FORMULAS_REFERENCIA_FK FOREIGN KEY (CODREFERENCIA) REFERENCES REFERENCIA(CODREFERENCIA)
);

CREATE TABLE NORMALIDADE (
    CODNORMALIDADE INT AUTO_INCREMENT PRIMARY KEY,
    CODVARIAVEL INT NOT NULL,
    CODREFERENCIA INT,
    VALORMIN DECIMAL(18,6),
    VALORMAX DECIMAL(18,6),
    SEXO CHAR(1),
    IDADE_MIN INT,  -- Idade mínima da faixa etária
    IDADE_MAX INT,  -- Idade máxima da faixa etária
    CONSTRAINT NORMALIDADE_VARIAVEL_FK FOREIGN KEY (CODVARIAVEL) REFERENCES VARIAVEIS(CODVARIAVEL),
    CONSTRAINT NORMALIDADE_REFERENCIA_FK FOREIGN KEY (CODREFERENCIA) REFERENCES REFERENCIA(CODREFERENCIA)
);

CREATE TABLE FORMULA_VARIAVEL (
    CODFORMULA_VARIAVEL INT AUTO_INCREMENT PRIMARY KEY,
    CODFORMULA INT NOT NULL,
    CODVARIAVEL INT NOT NULL,
    PADRAO BOOLEAN,
    CONSTRAINT FORMULA_VARIAVEL_CODFORMULA_FK FOREIGN KEY (CODFORMULA) REFERENCES FORMULAS(CODFORMULA),
    CONSTRAINT FORMULA_VARIAVEL_CODVARIAVEL_FK FOREIGN KEY (CODVARIAVEL) REFERENCES VARIAVEIS(CODVARIAVEL)
);

CREATE TABLE ANEXOS (
    CODANEXO INT AUTO_INCREMENT PRIMARY KEY,
    CODREFERENCIA INT NOT NULL,  -- Relacionamento com a tabela TB_REFERENCIA
    DESCRICAO VARCHAR(255),
    NOME VARCHAR(255),
    LINK VARCHAR(255),           -- Link do estudo
    CAMINHO VARCHAR(255),         -- Caminho do arquivo no computador
    CONSTRAINT ANEXOS_REFERENCIA_FK FOREIGN KEY (CODREFERENCIA) REFERENCES REFERENCIA(CODREFERENCIA)
);
